# Generated by Django 5.1.3 on 2024-11-25 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout', models.IntegerField(choices=[(0, 'Saída'), (1, 'Entrada')], default=0)),
                ('name', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout', models.IntegerField(choices=[(0, 'Saída'), (1, 'Entrada')], default=0)),
                ('title', models.TextField(max_length=45, null=True)),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('description', models.TextField(max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='perfil principal', max_length=45)),
                ('registries', models.ManyToManyField(to='api.registry')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=True)),
                ('edit', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='users',
            field=models.ManyToManyField(through='api.UserProfileRules', to=settings.AUTH_USER_MODEL),
        ),
    ]
