# Generated by Django 5.1.3 on 2024-11-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('default', models.TextField(default='', max_length=255)),
                ('title', models.TextField(max_length=45)),
                ('description', models.TextField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OptionInfoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(to='api.infofield')),
            ],
        ),
        migrations.AddField(
            model_name='infofield',
            name='options',
            field=models.ManyToManyField(null=True, to='api.optioninfofield'),
        ),
    ]
