# Generated by Django 5.1.3 on 2024-11-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groupfield_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infofield',
            name='options',
        ),
        migrations.DeleteModel(
            name='GroupField',
        ),
        migrations.DeleteModel(
            name='InfoField',
        ),
        migrations.DeleteModel(
            name='OptionInfoField',
        ),
    ]
