# Generated by Django 5.1.3 on 2024-11-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_infofield_options_delete_groupfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilerules',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
