# Generated by Django 5.1.3 on 2024-11-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_delete_user'),
        ('login', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
