# Generated by Django 5.1.3 on 2024-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout', models.IntegerField(choices=[(0, 'Saída'), (1, 'Entrada')], default=0)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout', models.IntegerField(choices=[(0, 'Saída'), (1, 'Entrada')], default=0)),
                ('title', models.TextField(max_length=45)),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('description', models.TextField(max_length=255)),
                ('categories', models.ManyToManyField(to='data.category')),
            ],
        ),
    ]
