# Generated by Django 5.1.3 on 2024-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_registry_description_alter_registry_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='title',
            field=models.TextField(max_length=45, null=True),
        ),
    ]
