# Generated by Django 5.1.3 on 2024-11-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_profile_alter_category_name_userprofilerules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='perfil principal', max_length=45),
        ),
    ]
